version: "3.3"

services:
  api_service:
    build: ../
    restart: always
    ports:
      - ${API_PORT_SERVER}:8080
    depends_on:
      - mongodb
  mongodb:
    image: mongo:5.0
    restart: always
    ports:
      - ${MONGO_PORT}:27017